"""Built-in default document categories and keyword hints for the rule fallback."""

from __future__ import annotations

# Built-in default taxonomy. Users can replace or extend this via config YAML.
DEFAULT_CATEGORIES: list[str] = [
    "invoice",
    "contract",
    "report",
    "resume",
    "manual",
    "academic_paper",
    "documentation",
    "receipt",
    "purchase_order",
    "quotation",
    "credit_note",
    "statement_of_account",
    "balance_sheet",
    "income_statement",
    "cash_flow_statement",
    "tax_return",
    "audit_report",
    "budget",
    "business_plan",
    "pitch_deck",
    "memorandum",
    "agenda",
    "meeting_minutes",
    "policy",
    "procedure",
    "standard_operating_procedure",
    "employee_handbook",
    "offer_letter",
    "job_description",
    "performance_appraisal",
    "timesheet",
    "payroll_register",
    "non_disclosure_agreement",
    "service_level_agreement",
    "master_services_agreement",
    "lease_agreement",
    "partnership_agreement",
    "articles_of_incorporation",
    "bylaws",
    "shareholder_agreement",
    "patent",
    "trademark",
    "copyright",
    "power_of_attorney",
    "will",
    "trust_deed",
    "deed_of_sale",
    "bill_of_sale",
    "promissory_note",
    "affidavit",
    "subpoena",
    "summons",
    "brief",
    "writ",
    "deposition",
    "pleading",
    "petition",
    "settlement_agreement",
    "privacy_policy",
    "terms_of_service",
    "disclaimer",
    "compliance_report",
    "certificate_of_analysis",
    "bill_of_lading",
    "packing_list",
    "commercial_invoice",
    "certificate_of_origin",
    "customs_declaration",
    "shipping_manifest",
    "manifest",
    "waybill",
    "delivery_note",
    "thesis",
    "dissertation",
    "research_paper",
    "essay",
    "journal_article",
    "textbook",
    "syllabus",
    "lecture_notes",
    "transcript",
    "diploma",
    "certificate",
    "portfolio",
    "white_paper",
    "case_study",
    "specification",
    "schematic",
    "blueprint",
    "user_guide",
    "quick_start_guide",
    "troubleshooting_guide",
    "release_notes",
    "api_documentation",
    "data_sheet",
    "brochure",
    "flyer",
    "catalog",
    "press_release",
    "newsletter",
    "poster",
    "curriculum_vitae",
    "cover_letter",
    "biodata",
    "application_form",
    "medical_record",
    "prescription",
    "lab_report",
    "chart",
    "discharge_summary",
    "insurance_policy",
    "insurance_claim",
    "architectural_plan",
    "map",
    "diagram",
    "storyboard",
    "script",
    "screenplay",
    "score",
    "sheet_music",
    "will_and_testament",
    "passport",
    "visa",
    "birth_certificate",
    "death_certificate",
    "marriage_certificate",
    "driver_license",
    "identification_card",
    "deed",
    "land_title",
    "survey_plat",
    "other",
]

# Extra keyword hints used by the rule-based fallback, keyed by category.
# Category names themselves are always matched (with underscores expanded),
# these are additional synonyms/phrases that improve recall.
CATEGORY_KEYWORDS: dict[str, tuple[str, ...]] = {
    "invoice": ("bill to", "amount due", "invoice number", "payment terms", "subtotal", "vat"),
    "receipt": ("paid in full", "thank you for your purchase", "transaction id", "cashier"),
    "contract": ("agreement", "parties", "terms and conditions", "effective date", "signature", "clause"),
    "resume": ("work experience", "education", "skills", "objective", "employment history"),
    "curriculum_vitae": ("curriculum vitae", "publications", "academic background", "cv"),
    "cover_letter": ("dear hiring manager", "i am writing to apply", "sincerely"),
    "job_description": ("responsibilities", "qualifications", "requirements", "reports to", "role overview"),
    "offer_letter": ("we are pleased to offer", "start date", "compensation", "position of"),
    "report": ("summary", "findings", "conclusion", "overview", "results"),
    "academic_paper": ("abstract", "references", "introduction", "methodology", "keywords"),
    "research_paper": ("abstract", "literature review", "methodology", "conclusion", "doi"),
    "thesis": ("thesis", "advisor", "dissertation committee", "chapter"),
    "manual": ("instructions", "how to use", "safety precautions", "table of contents"),
    "user_guide": ("getting started", "how to", "step 1", "navigation"),
    "documentation": ("documentation", "reference", "usage", "examples", "configuration"),
    "api_documentation": ("endpoint", "request", "response", "api key", "http", "json"),
    "release_notes": ("release notes", "changelog", "bug fixes", "new features", "version"),
    "meeting_minutes": ("minutes", "attendees", "action items", "motions", "adjourned"),
    "agenda": ("agenda", "topics", "time", "presenter", "discussion items"),
    "memorandum": ("memo", "to:", "from:", "subject:", "cc:"),
    "policy": ("policy", "purpose", "scope", "compliance", "responsibility"),
    "standard_operating_procedure": ("sop", "standard operating procedure", "procedure steps"),
    "non_disclosure_agreement": ("confidential", "non-disclosure", "nda", "proprietary information"),
    "service_level_agreement": ("sla", "service level", "uptime", "response time", "penalties"),
    "lease_agreement": ("landlord", "tenant", "rent", "lease term", "premises"),
    "privacy_policy": ("personal data", "privacy", "gdpr", "data controller", "cookies"),
    "terms_of_service": ("terms of service", "terms of use", "user agreement", "governing law"),
    "purchase_order": ("purchase order", "po number", "ship to", "bill to", "quantity"),
    "quotation": ("quotation", "quote", "valid until", "unit price", "we are pleased to quote"),
    "balance_sheet": ("assets", "liabilities", "equity", "balance sheet", "total current"),
    "income_statement": ("revenue", "expenses", "net income", "profit and loss", "gross margin"),
    "cash_flow_statement": ("cash flow", "operating activities", "investing activities", "financing activities"),
    "tax_return": ("tax return", "taxable income", "irs", "form 1040", "deductions", "withholding"),
    "audit_report": ("audit", "auditor", "internal controls", "material misstatement", "opinion"),
    "budget": ("budget", "forecast", "allocation", "fiscal year", "projected"),
    "business_plan": ("business plan", "market analysis", "executive summary", "revenue model"),
    "pitch_deck": ("pitch", "investors", "traction", "go-to-market", "funding"),
    "insurance_policy": ("policy number", "premium", "coverage", "insured", "deductible"),
    "insurance_claim": ("claim number", "claimant", "loss", "adjuster", "settlement amount"),
    "medical_record": ("patient", "diagnosis", "medical history", "physician", "treatment"),
    "prescription": ("rx", "prescription", "dosage", "pharmacy", "take daily"),
    "lab_report": ("lab", "specimen", "reference range", "assay", "results"),
    "certificate": ("certificate", "hereby certifies", "awarded to", "in recognition of"),
    "patent": ("patent", "claims", "invention", "prior art", "embodiment"),
    "trademark": ("trademark", "mark", "goods and services", "registration number"),
    "power_of_attorney": ("power of attorney", "attorney-in-fact", "principal", "hereby appoint"),
    "will": ("last will", "testament", "executor", "beneficiary", "bequest"),
    "deed": ("deed", "grantor", "grantee", "convey", "parcel"),
    "passport": ("passport", "nationality", "date of birth", "passport number", "issuing authority"),
    "birth_certificate": ("birth certificate", "date of birth", "place of birth", "registrar"),
    "driver_license": ("driver license", "driving licence", "license number", "class", "expiration"),
    "bill_of_lading": ("bill of lading", "consignee", "shipper", "port of loading", "carrier"),
    "packing_list": ("packing list", "carton", "net weight", "gross weight", "contents"),
    "delivery_note": ("delivery note", "delivered", "received by", "goods delivered"),
    "waybill": ("waybill", "airway bill", "tracking number", "consignment"),
    "customs_declaration": ("customs", "hs code", "declaration", "import", "duty"),
    "white_paper": ("white paper", "whitepaper", "in-depth", "authoritative"),
    "case_study": ("case study", "challenge", "solution", "outcome", "client"),
    "specification": ("specification", "requirements", "shall", "compliance matrix"),
    "data_sheet": ("datasheet", "data sheet", "technical specifications", "electrical characteristics"),
    "press_release": ("press release", "for immediate release", "media contact", "announces"),
    "newsletter": ("newsletter", "subscribe", "this month", "highlights"),
    "brochure": ("brochure", "learn more", "features", "contact us"),
    "catalog": ("catalog", "catalogue", "product listing", "price list"),
    "syllabus": ("syllabus", "course", "grading", "assignments", "semester"),
    "lecture_notes": ("lecture", "notes", "professor", "topic"),
    "transcript": ("transcript", "grades", "gpa", "credits", "semester"),
    "diploma": ("diploma", "graduation", "degree", "conferred"),
    "timesheet": ("timesheet", "hours worked", "time sheet", "overtime"),
    "payroll_register": ("payroll", "gross pay", "net pay", "deductions", "pay period"),
    "performance_appraisal": ("appraisal", "performance review", "goals", "rating", "reviewer"),
    "employee_handbook": ("handbook", "employee", "code of conduct", "benefits", "workplace policies"),
    "application_form": ("application form", "applicant", "please complete", "section a"),
    "settlement_agreement": ("settlement", "release of claims", "settling parties", "consideration"),
    "affidavit": ("affidavit", "sworn", "deponent", "notary", "solemnly affirm"),
    "subpoena": ("subpoena", "you are hereby commanded", "court", "testify"),
    "summons": ("summons", "plaintiff", "defendant", "respond within", "court"),
    "discharge_summary": ("discharge", "admission date", "discharge date", "hospital", "follow-up"),
    "compliance_report": ("compliance", "regulatory", "audit findings", "remediation"),
    "credit_note": ("credit note", "credit memo", "refund", "adjustment"),
    "statement_of_account": ("statement", "account number", "previous balance", "payments received"),
    "other": (),
}
